/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Vitals;
import Model.VitalsHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sathya
 */
public class viewReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewReportPanel
     */
    
    VitalsHistory vitalHistory;
    Vitals local_vital ;
    
    public viewReportPanel(VitalsHistory vitalHistory) {
        initComponents();
        this.vitalHistory = vitalHistory;
        this.local_vital = new Vitals();
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportHistoryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewReportDetailBtn = new javax.swing.JButton();
        deleteReportDetailBtn = new javax.swing.JButton();
        temperatureTextField = new javax.swing.JTextField();
        bloodPressureTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();

        jLabel1.setText("Patient Reports History");

        reportHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Temperature", "Blood Pressure", "Pulse", "Date"
            }
        ));
        jScrollPane1.setViewportView(reportHistoryTable);

        jLabel2.setText("Temperature");

        jLabel3.setText("Blood Pressure");

        jLabel4.setText("Pulse");

        jLabel5.setText("Date");

        viewReportDetailBtn.setText("View Report in Detail");
        viewReportDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportDetailBtnActionPerformed(evt);
            }
        });

        deleteReportDetailBtn.setText("Delete Report");
        deleteReportDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReportDetailBtnActionPerformed(evt);
            }
        });

        temperatureTextField.setEditable(false);
        temperatureTextField.setBackground(new java.awt.Color(255, 255, 255));

        bloodPressureTextField.setEditable(false);
        bloodPressureTextField.setBackground(new java.awt.Color(255, 255, 255));

        pulseTextField.setEditable(false);
        pulseTextField.setBackground(new java.awt.Color(255, 255, 255));

        dateTextField.setEditable(false);
        dateTextField.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(viewReportDetailBtn)
                                .addGap(38, 38, 38)
                                .addComponent(deleteReportDetailBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewReportDetailBtn)
                    .addComponent(deleteReportDetailBtn))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewReportDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportDetailBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) reportHistoryTable.getModel();
        int index = reportHistoryTable.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(this, "Select a row to view details");
            return;
        }
        this.local_vital = (Vitals) model.getValueAt(index, 3);
        
        
        temperatureTextField.setText(Float.toString(this.local_vital.getTemperature()));
        bloodPressureTextField.setText(Integer.toString(this.local_vital.getBloodPressure()));
        pulseTextField.setText(Integer.toString(this.local_vital.getPulse()));
        dateTextField.setText(this.local_vital.getDate());
    }//GEN-LAST:event_viewReportDetailBtnActionPerformed

    private void deleteReportDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReportDetailBtnActionPerformed
        // TODO add your handling code here:
        int index = reportHistoryTable.getSelectedRow();
        
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Select a row to delete Vitals");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) reportHistoryTable.getModel();
        this.local_vital = (Vitals) model.getValueAt(index, 3);
        this.vitalHistory.deleteVitalsFromVitalsObject(this.local_vital);
        JOptionPane.showMessageDialog(this, "Deleted Successfully");
        
        this.temperatureTextField.setText("");
        this.bloodPressureTextField.setText("");
        this.pulseTextField.setText("");
        this.dateTextField.setText("");
        
        populateTable();
        
    }//GEN-LAST:event_deleteReportDetailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteReportDetailBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTable reportHistoryTable;
    private javax.swing.JTextField temperatureTextField;
    private javax.swing.JButton viewReportDetailBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel tableModel = (DefaultTableModel) reportHistoryTable.getModel();
        tableModel.setRowCount(0);
        
        for(Vitals iter : this.vitalHistory.getArrayVitals()){
            Object[] obj = new Object[4];
            obj[0] = String.valueOf(iter.getTemperature());
            obj[1] = String.valueOf(iter.getBloodPressure());
            obj[2] = String.valueOf(iter.getPulse());
            obj[3] = iter;
            System.out.println("populate mothod" + iter);
            
            tableModel.addRow(obj);
                  
        }
    }
}
