/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 *
 * @author Sathya
 */
public class AccountManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form accountManagementPanel
     */
    
    AccountDirectory accountDirectory;
    JPanel workArea;
    
    public AccountManagementPanel(JPanel workArea, AccountDirectory accountDirectory) {
        initComponents();
        this.accountDirectory = accountDirectory;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createAccBtn = new javax.swing.JButton();
        manageAccBtn = new javax.swing.JButton();

        jLabel1.setText("Account Management");

        createAccBtn.setText("Create Account");
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });

        manageAccBtn.setText("Manage Account");
        manageAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAccBtn)
                    .addComponent(createAccBtn))
                .addContainerGap(730, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(createAccBtn)
                .addGap(33, 33, 33)
                .addComponent(manageAccBtn)
                .addContainerGap(439, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel createAccJPanel = new CreateAccountJPanel(this.workArea, this.accountDirectory);
        this.workArea.add("CreateAccountJPanel",createAccJPanel);
        CardLayout cardLayout = (CardLayout)this.workArea.getLayout();
        cardLayout.next(this.workArea);
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void manageAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccBtnActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel managaAccPanel = new ManageAccountJPanel(this.workArea, this.accountDirectory);
        this.workArea.add("ManageAccountJPanel",managaAccPanel);
        CardLayout cardLayout = (CardLayout) this.workArea.getLayout();
        cardLayout.next(this.workArea);
        
    }//GEN-LAST:event_manageAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAccBtn;
    // End of variables declaration//GEN-END:variables
}
